### ISSUE TITLE
model/naampy_rmse not found on windows machine

### ISSUE THREAD

**Issue by saurabhzuve** [appeler/naampy#4]
hi thanks for the project
i was trying to use it on a windows machine and when i run
result = in_rolls_fn_gender(name_df, 'first_name')
i get the following error

OSError: No file or directory found at C:\ProgramData\Anaconda3\envs\saurabh\lib\site-packages\naampy\model/naampy_rmse

Please help what could be done

**Comment by rajashekar** [comment]
@saurabhzuve Thank you for raising this issue. 

This is fixed in the latest version naampy-0.4.2 , please uninstall and install again `pip install naampy` (please check you got the latest version sometimes pip may use cache you might get 0.4.1, if you get old version try uninstall and install again)

**Comment by LSYS** [comment]
@saurabhzuve @rajashekar 
I had the same error.
I've tried it again and confirm that it works.

**Comment by saurabhzuve** [comment]
Hi Thanks, It worked after installing for the latest version.
thanks for actively maintaining this. 
 : )
